// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjvodfeahmjgyvzjowxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqdm9kZmVhaG1qZ3l2empvd3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODAxMDUsImV4cCI6MjA3MzY1NjEwNX0.SGf_26o1YMuLQzfHCFOtbyfFtJ9Du8QTFntPbBtPiaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});